plugins {
    id 'java'
    id 'maven-publish'
}

base.archivesName = archive_name
java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.ow2.asm:asm-commons:$asm_version"
    implementation "org.ow2.asm:asm-util:$asm_version"
    implementation "org.jspecify:jspecify:$jspecify_version"
}

java {
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = group
            artifactId = archive_name
            version = version
            from components.java

            pom {
                name = archive_name
                description = maven_description
            }
        }
    }
    repositories {
        maven {
            credentials {
                username repsyUsername
                password repsyPassword
            }
            url maven_url
        }
    }
}
