# Project
group = com.fiskmods.quantify
archive_name = quantify
version = 2.2.1

# Dependencies
java_version = 21
asm_version = [9.0,)
jspecify_version = [1.0,)

# Publishing
maven_url = https://repo.repsy.io/mvn/fiskfille/fiskmods/
maven_description = A lightweight library for compiling and running scripts written in the Quantify scripting language.
